version: "3.8"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1.2-apache
    ports:
      - "8976:80"
      - "8977:443"
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html

  database:
    image: 'mariadb'
    restart: always
    volumes:
      - ./migration/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: password



  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8899:80'
    environment:
      - PMA_ARBITRARY=1

volumes:
  src: